#include <cut.h>

CUT_INCLUDE_MODULE(ClientTest);
CUT_INCLUDE_MODULE(GroupTest);
CUT_INCLUDE_MODULE(ListClientsTest);
CUT_INCLUDE_MODULE(ConfigTest);
CUT_INCLUDE_MODULE(DatabaseTest);

CUT_DEFINE_MAIN
    CUT_CALL_TESTS_FROM_MODULE(ConfigTest);
    CUT_CALL_TESTS_FROM_MODULE(ClientTest);
    CUT_CALL_TESTS_FROM_MODULE(GroupTest);
    CUT_CALL_TESTS_FROM_MODULE(ListClientsTest);
    CUT_CALL_TESTS_FROM_MODULE(DatabaseTest);
CUT_END_MAIN
